"""
Static Spanish copy strings and small lookup tables used across
router.py and dispatch.py.
"""

HELP_TEXT = (
    "*Comandos disponibles:*\n\n"
    "*Gastos*\n"
    "• _gasté 5000 en almuerzo_\n"
    "• _pagué 3000_ (sin categoría, te pregunto)\n"
    "• _gasté 18000 en supermercado pan, leche, queso, lavalozas_ — batch\n"
    "• _confirmar_ / _cancelar_ — responde cuando te pregunte\n"
    "• _resumen_ — resumen semanal\n\n"
    "*Presupuesto*\n"
    "• _presupuesto 600.000_\n\n"
    "*Pendientes*\n"
    "• _pendiente llamar al banco_\n"
    "• _mis pendientes_\n"
    "• _listo: llamar al banco_\n"
    "• _borrar pendiente llamar al banco_\n\n"
    "*Compras*\n"
    "• _necesito comprar shampoo y balsamo_ — te pregunto dónde guardarlo\n"
    "• _comprar leche_\n"
    "• _compras_ — ver lista\n"
    "• _compré leche_ — marcar como comprado\n\n"
    "*Esperando*\n"
    "• _esperando respuesta del seguro_\n"
    "• _mis esperas_\n"
    "• _llegó seguro_ — marcar como resuelto\n\n"
    "*Despensa*\n"
    "• _despensa cocina arroz 3_ — agregar con categoría\n"
    "• _despensa jabón 2_ — agregar (sin categoría → otros)\n"
    "• _mi despensa_ — ver stock\n"
    "• _usé jabón_ — consumir uno\n"
    "• _compré jabón_ — reponer uno\n"
    "• _compré jabón 3_ — reponer sumando 3\n"
    "• _stock 2 jabón_ o _stock jabón 2_ — fijar stock exacto\n"
    "• _compré todo_ — reponer todo lo que falta\n\n"
    "*Recetas*\n"
    "• _nueva receta: cazuela_ — crear receta (con IA si está activa)\n"
    "• _mis recetas_ — ver todas\n"
    "• _receta cazuela_ — ver ingredientes\n"
    "• _qué puedo hacer_ — recetas con lo que tienes en tu despensa\n"
    "• _qué cocino_ — sugerencias de nuevas recetas con IA\n"
    "• _elegir 2_ — elegir una sugerencia después de pedirlas\n\n"
    "Escribe *ayuda* en cualquier momento para ver esto.\n\n"
    "*Tu perfil*\n"
    "• _me llamo Bruno_ — guardar tu nombre\n\n"
    "*Tablero*\n"
    "• _tablero_ — link al dashboard web"
)

WELCOME_TEXT = (
    "¡Hola! Soy Cazuela, tu asistente personal por WhatsApp.\n\n"
    "*Lo que puedo hacer:*\n"
    "• *Gastos* — _gasté 5000 en almuerzo_ · _resumen_\n"
    "• *Presupuesto* — _presupuesto 600.000_\n"
    "• *Pendientes* — _pendiente llamar al banco_\n"
    "• *Lista de compras* — _comprar leche_\n"
    "• *Esperando* — _esperando respuesta del seguro_\n"
    "• *Despensa* — _despensa cocina arroz 3_\n"
    "• *Recetas* — _nueva receta: cazuela_\n"
    "• *Tablero web* — _tablero_\n\n"
    "Escribe *ayuda* para ver todos los comandos.\n\n"
    "¿Cómo te llamo? Escribe *me llamo [tu nombre]* para que te recuerde."
)

_PANTRY_CATEGORIES = {1: "cocina", 2: "baño", 3: "otros"}

_CATEGORY_PROMPT = (
    "¿En qué categoría?\n"
    "_elegir 1_ Cocina · _elegir 2_ Baño · _elegir 3_ Otros\n"
    "O _cancelar_ para no guardar."
)
